### ISSUE TITLE
[ui] detail / 책 상세 뷰 구현

### ISSUE THREAD

**Issue by b1urrrr** [SOPT-TEAM6-Aladin/Aladin-AOS#10]
## ISSUE
- detail / 책 상세 뷰 구현

## To-Do
- [x] 툴바 구현
- [x] 공통 버튼 bg 구현
- [x] 더보기 버튼 구현 (책소개, 목차, 줄거리)
- [x] 하단 탭 구현 (찜, 장바구니, 구매하기)
- [x] 찜 selector 구현
