### ISSUE TITLE
[ui/feat] detail / 책 상세 뷰 액티비티 구현

### ISSUE THREAD

**Issue by b1urrrr** [SOPT-TEAM6-Aladin/Aladin-AOS#22]
## ISSUE
- 책 상세 뷰 액티비티 구현 (DetailActivtiy)

## To-Do
- [x] 기본 버튼 연결 (뒤로가기, 장바구니 목록 조회)
- [x] 더보기 버튼 구현 (책 소개, 목차, 줄거리)
- [x] 책 상세 정보 조회 API 연결
- [x] 장바구니 담기 API 연결
- [x] 좋아요 API 연결
